In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Se lee el dataframe de entrenamiento

In [2]:
df = pd.read_csv('chipless_set_train.csv')

In [3]:
df

,0,1,2,3,4,5,6,7,8,9,...,1593,1594,1595,1596,1597,1598,1599,1600,Tag_names,Interval
0,-49.84765,-49.24805,-51.23632,-50.73828,-50.91991,-51.94921,-55.00195,-52.63085,-50.11328,-48.79296,...,-55.10351,-53.99023,-56.16211,-56.75976,-55.18945,-56.44531,-54.29101,-54.43749,tag_01011_4x4,130_140
1,-49.37109,-50.94921,-51.36132,-50.89648,-50.52148,-50.15820,-53.02929,-54.01172,-51.91796,-49.42773,...,-51.48242,-50.90234,-51.96484,-51.84765,-50.63477,-51.65820,-50.54101,-50.96289,tag_01011_4x4,130_140
2,-56.00586,-57.75000,-59.42773,-54.29492,-53.82617,-53.39257,-54.86133,-53.20898,-51.55859,-51.50000,...,-50.35937,-50.55273,-50.50976,-50.61328,-51.49219,-51.19726,-52.79687,-52.25976,tag_01011_4x4,130_140
3,-52.21289,-52.22851,-54.00585,-50.19726,-48.72070,-47.76367,-49.77344,-49.65625,-49.52538,-48.41015,...,-50.09375,-49.80078,-50.69726,-50.01171,-50.29297,-51.03125,-51.90234,-51.49023,tag_01011_4x4,130_140
4,-50.72460,-52.68945,-53.78906,-51.36132,-50.32227,-50.49023,-52.85351,-51.92773,-51.66016,-49.77929,...,-52.26563,-52.11132,-52.16601,-52.42773,-51.76562,-50.72070,-50.26562,-50.61523,tag_01011_4x4,130_140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10095,-47.72656,-49.83984,-48.20703,-46.15039,-44.11914,-42.93554,-43.11132,-43.15820,-43.22851,-43.20313,...,-40.28906,-41.78906,-41.64453,-41.93749,-41.57227,-42.29882,-42.30469,-42.08008,tag_00001_4x4,050_080
10096,-51.27148,-54.10742,-50.07421,-48.23828,-45.76953,-45.46484,-45.49414,-46.35547,-46.48046,-47.13672,...,-36.57422,-35.72656,-35.88476,-35.60547,-35.30664,-35.37890,-35.53711,-35.55859,tag_00001_4x4,050_080
10097,-54.35741,-64.63281,-61.41211,-53.58593,-49.64648,-47.64453,-47.81446,-48.43945,-48.19530,-47.61328,...,-33.70312,-33.65234,-33.96289,-33.73437,-33.63476,-33.69531,-33.75586,-33.63476,tag_00001_4x4,050_080
10098,-51.09765,-56.34375,-54.06836,-50.52539,-47.16992,-44.94726,-46.02148,-46.38476,-45.73828,-45.86914,...,-43.37695,-45.25391,-45.79492,-45.52148,-45.14648,-45.53711,-46.14258,-45.34570,tag_00001_4x4,050_080
10099,-45.84961,-47.50000,-47.02734,-44.56445,-42.96094,-42.09374,-42.63867,-43.01171,-42.87305,-43.09179,...,-33.15430,-33.01758,-33.47265,-33.33984,-33.19140,-33.37500,-33.07226,-32.76562,tag_00001_4x4,050_080

Leemos el df de entrenamiento por ahora solo para observar su estructura

In [6]:
df_test = pd.read_csv('chipless_set_test_noLabel.csv')
df_test = df_test.drop(columns=['index'])
df_test

,0,1,2,3,4,5,6,7,8,9,...,1592,1593,1594,1595,1596,1597,1598,1599,1600,Interval
0,-41.05859,-45.22265,-48.47461,-45.05859,-43.61133,-42.35547,-40.64453,-40.85742,-42.40039,-43.41210,...,-60.11523,-62.47265,-59.79882,-56.03906,-55.16602,-54.63672,-51.07226,-50.07617,-49.36523,050_080
1,-41.71875,-44.71289,-47.19140,-45.77148,-44.66210,-42.69531,-41.38476,-42.18163,-43.33008,-45.00000,...,-46.80469,-46.39844,-46.28125,-46.27149,-46.21289,-46.14648,-46.70312,-46.02929,-46.94531,050_080
2,-44.21094,-50.81836,-60.81640,-47.71289,-44.87500,-43.44727,-42.53125,-43.33593,-45.64649,-48.16211,...,-48.77148,-48.52539,-48.75195,-49.96679,-49.74218,-49.30859,-50.41406,-49.83007,-51.59765,050_080
3,-45.32812,-50.61718,-52.30273,-45.50977,-43.71094,-42.24609,-40.83789,-41.65625,-43.84570,-47.07227,...,-51.55663,-54.43749,-54.77929,-57.38867,-56.53710,-57.20508,-58.11718,-60.58594,-65.33593,050_080
4,-44.56055,-48.62890,-52.46288,-45.85742,-43.56641,-42.42383,-41.15039,-41.82617,-43.71484,-47.30859,...,-49.12890,-49.18554,-49.19335,-48.46874,-47.80273,-48.78906,-48.25000,-47.58985,-48.03515,050_080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1425,-48.99023,-46.34179,-44.43359,-44.37500,-46.00390,-48.68750,-51.18554,-50.62109,-52.62695,-53.82813,...,-49.61719,-49.57031,-49.20703,-50.30468,-47.74804,-47.34961,-47.65429,-47.71680,-46.77930,130_140
1426,-48.53516,-46.49219,-44.67773,-43.86914,-44.97070,-47.18946,-51.29687,-53.51563,-55.00390,-57.08202,...,-54.14453,-54.46289,-53.09765,-52.75781,-50.98437,-50.81445,-50.83984,-50.19531,-51.00780,130_140
1427,-51.35156,-48.44921,-46.46680,-46.43164,-48.39453,-52.57421,-59.37890,-58.65624,-58.68750,-60.55859,...,-54.42968,-54.57226,-53.91602,-54.68554,-51.65429,-51.36132,-51.97460,-50.45116,-50.15038,130_140
1428,-56.33007,-51.62499,-48.89062,-47.68750,-49.25390,-52.49804,-60.39844,-73.67188,-67.64453,-69.40624,...,-52.82227,-51.79882,-52.93359,-51.95507,-54.37695,-54.20898,-53.49609,-52.37109,-53.09375,130_140
1429,-55.02539,-50.90234,-47.97852,-47.61328,-49.94141,-53.94921,-64.60155,-66.87500,-63.56054,-62.49609,...,-49.27929,-48.61523,-48.79296,-49.49804,-49.51562,-49.48632,-49.42187,-49.52343,-48.41797,130_140

In [13]:
# Mostrar el número de valores NaN por columna, pero solo las columnas con > 0 NaNs
na_counts = df.isna().sum()
na_counts = na_counts[na_counts > 0]
na_counts

Series([], dtype: int64)

In [29]:
#Tipos diferentes a float
print(df.dtypes[df.dtypes != float ])

#Valores unicos y cantidades
print((df['Tag_names'].unique()), (df['Tag_names'].nunique()))
print(df['Interval'].unique(), df['Interval'].nunique())

Tag_names    object
Interval     object
dtype: object
['tag_01011_4x4' 'tag_00001_4x4' 'tag_10000_4x4' 'tag_10101_4x4'
 'tag_00100_4x4' 'tag_11010_3x3' 'tag_01110_3x3' 'tag_10011_2x2'
 'tag_11001_2x2' 'tag_01000_2x2' 'tag_00010_2x2' 'tag_00111_2x2'
 'tag_10110_1x1' 'tag_11100_1x1' 'tag_11111_1x1' 'tag_01101_1x1'] 16
['130_140' '020_030' '060_070' '000_010' '050_080' '080_110' '110_130'] 7

In [30]:
#Desbalances
print(df['Tag_names'].value_counts().sort_values(ascending=False))
print(df['Interval'].value_counts().sort_values(ascending=False))

Tag_names
tag_01101_1x1    800
tag_11111_1x1    800
tag_00100_4x4    700
tag_01011_4x4    600
tag_10101_4x4    600
tag_11010_3x3    600
tag_10000_4x4    600
tag_00001_4x4    600
tag_10011_2x2    600
tag_01110_3x3    600
tag_11001_2x2    600
tag_01000_2x2    600
tag_00111_2x2    600
tag_00010_2x2    600
tag_11100_1x1    600
tag_10110_1x1    600
Name: count, dtype: int64
Interval
000_010    3200
050_080    1700
130_140    1600
080_110    1600
110_130    1600
060_070     200
020_030     200
Name: count, dtype: int64